[versions]
accompanistPager = "0.36.0"
accompanistPermissions = "0.36.0"
agp = "8.7.1"
api = "13.1.5"
coilCompose = "2.7.0"
commonsCompress = "1.27.1"
converterGson = "2.11.0"
converterScalars = "2.11.0"
datastorePreferences = "1.1.1"
documentfile = "1.0.1"
glide = "4.16.0"
gson = "2.11.0"
kotlin = "2.0.21"
junit = "4.13.2"
kotlinxSerializationJson = "1.7.3"
activityCompose = "1.9.3"
lifecycleViewmodelCompose = "2.8.6"
navigationCompose = "2.8.3"
navigationRuntimeKtx = "2.8.3"
okhttpVersion = "4.12.0"
provider = "13.1.5"
retrofit = "2.11.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
roomKtx = "2.6.1"
roomRuntime = "2.6.1"
rules = "1.6.1"
xz = "1.10"
xZipJbindingXandroid = "Release-16.02-2.02"
zip4j = "2.11.5"
roomVersion = "2.6.1"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistPermissions" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
api = { module = "dev.rikka.shizuku:api", version.ref = "api" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version = "2024.10.00" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
provider = { module = "dev.rikka.shizuku:provider", version.ref = "provider" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
material3 = { module = "androidx.compose.material3:material3" }
x-zip-jbinding-xandroid = { module = "com.github.omicronapps:7-Zip-JBinding-4Android", version.ref = "xZipJbindingXandroid" }
xz = { module = "org.tukaani:xz", version.ref = "xz" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
androidx-roomcompiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
desugar = "com.android.tools:desugar_jdk_libs_nio:2.1.2"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.26" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.0.21" }
